### ISSUE TITLE
add a readme file

### ISSUE THREAD

**Issue by ghost** [blondieblue-eyes/helpeducateme#1]
A repository is a project generally, self contained, that means it does not depend on other projects to serve something (generally). What is this inended for ? You can edit the README file. If you just like coding and do not know where to start, I will show you some easy HTML / CSS tutorials to start making beautiful web pages, and that you can even host directly in Github and show to your friends.

**Comment by blondieblue-eyes** [comment]
Thank u very much. Go easy. Its is alot.to learn.

Thx.

**Comment by ghost** [comment]
You would like to start with this https://www.codecademy.com/learn/learn-html 
give it a try then tell me, 
Try to use Brackets for writing code. It is good because you see instantly changes of code in a webpage in a browser (this is what we call what you see is what you get)

**Comment by ghost** [comment]
Or better start with **https://www.w3schools.com/html/** without really coding at all. Just seeing, noting, and trying to answer questions

**Comment by ghost** [comment]
to download brackets  head to **http://brackets.io/** and then download / install, also use Chrome only not another browser.

**Comment by blondieblue-eyes** [comment]
I'm ap sorry its taken me forever to remevwr that 9 did still have the email to beagle to log in to github  I am completely new  I barely have learned anything in over 3 years and spenta hours n hours reading the flor charts and  took me almost a year to understand some of what I was readying that just on my phone itself not even off the pc....
